import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, Pressable,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors, Spacing, Radius, FontSize } from '@/constants/theme';
import { MOCK_PROPERTIES } from '@/constants/mockData';

export default function QRManagerScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { propertyId } = useLocalSearchParams<{ propertyId: string }>();
  const [regenerating, setRegenerating] = useState(false);

  const property = MOCK_PROPERTIES.find(p => p.id === propertyId) ?? MOCK_PROPERTIES[0];

  const handleRegenerate = () => {
    setRegenerating(true);
    setTimeout(() => setRegenerating(false), 1500);
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <Pressable style={styles.back} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={22} color={Colors.text} />
        </Pressable>
        <View style={styles.headerInfo}>
          <Text style={styles.title}>QR Code</Text>
          <Text style={styles.subtitle}>{property.name}</Text>
        </View>
        <View style={styles.genBadge}>
          <Text style={styles.genText}>Active · Generation 2</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={styles.qrCard}>
          <View style={styles.qrBox}>
            <View style={styles.qrFrame}>
              <Ionicons name="qr-code" size={120} color={Colors.text} />
            </View>
          </View>
          <Text style={styles.qrLabel}>SCAN TO REQUEST VISIT</Text>
          <View style={styles.tokenBox}>
            <Text style={styles.tokenLabel}>OR ENTER CODE</Text>
            <Text style={styles.tokenValue}>{property.qrToken}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>ACTIONS</Text>

        <View style={styles.actionsCard}>
          <ActionRow icon="download-outline" label="Download PNG" />
          <ActionRow icon="document-outline" label="Download print PDF (A4)" />
          <ActionRow icon="print-outline" label="Print directly" />
          <ActionRow
            icon="share-social-outline"
            label="Share via WhatsApp"
            onPress={() => {}}
          />
        </View>

        <Text style={styles.sectionTitle}>QR SETTINGS</Text>

        <View style={styles.settingsCard}>
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingLabel}>QR is active</Text>
              <Text style={styles.settingDesc}>Brokers can scan or enter code right now</Text>
            </View>
            <View style={styles.activeDot} />
          </View>

          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingLabel}>Token</Text>
              <Text style={styles.settingDesc}>
                Generated by {property.caretakerName} on 8 May
              </Text>
            </View>
            <Text style={styles.tokenSmall}>{property.qrToken}</Text>
          </View>
        </View>

        <View style={styles.regenCard}>
          <Pressable style={styles.regenBtn} onPress={handleRegenerate}>
            <Ionicons name="refresh-outline" size={18} color={regenerating ? Colors.textMuted : Colors.primary} />
            <Text style={[styles.regenBtnText, regenerating && styles.regenBtnTextLoading]}>
              {regenerating ? 'Regenerating…' : 'Regenerate QR & code'}
            </Text>
          </Pressable>
          <Text style={styles.regenNote}>
            Old QR will stop working immediately. Pending approvals keep their approval.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

function ActionRow({ icon, label, onPress }: any) {
  return (
    <Pressable style={styles.actionRow} onPress={onPress ?? (() => {})}>
      <View style={styles.actionIcon}>
        <Ionicons name={icon} size={18} color={Colors.primary} />
      </View>
      <Text style={styles.actionLabel}>{label}</Text>
      <Ionicons name="chevron-forward" size={16} color={Colors.textMuted} />
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.sm,
    paddingHorizontal: Spacing.md, paddingVertical: Spacing.md,
    backgroundColor: Colors.card, borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  back: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.background, alignItems: 'center', justifyContent: 'center' },
  headerInfo: { flex: 1 },
  title: { fontSize: FontSize.lg, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: FontSize.sm, color: Colors.textSecondary },
  genBadge: { backgroundColor: Colors.successLight, paddingHorizontal: Spacing.sm, paddingVertical: 4, borderRadius: Radius.full },
  genText: { fontSize: FontSize.xs, fontWeight: '600', color: Colors.success },
  scroll: { padding: Spacing.md, paddingBottom: 40 },
  qrCard: {
    backgroundColor: Colors.card, borderRadius: Radius.xl,
    padding: Spacing.xl, alignItems: 'center',
    marginBottom: Spacing.lg, borderWidth: 1, borderColor: Colors.border,
  },
  qrBox: { marginBottom: Spacing.md },
  qrFrame: {
    width: 200, height: 200, borderRadius: Radius.lg,
    borderWidth: 2, borderColor: Colors.border,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: Colors.background,
  },
  qrLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, letterSpacing: 1, marginBottom: Spacing.md },
  tokenBox: { alignItems: 'center' },
  tokenLabel: { fontSize: FontSize.xs, fontWeight: '600', color: Colors.textSecondary, letterSpacing: 0.8, marginBottom: 4 },
  tokenValue: { fontSize: FontSize.xxxl, fontWeight: '900', color: Colors.text, letterSpacing: 4 },
  sectionTitle: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textMuted, letterSpacing: 0.8, marginBottom: Spacing.sm, marginTop: Spacing.sm },
  actionsCard: {
    backgroundColor: Colors.card, borderRadius: Radius.lg,
    overflow: 'hidden', marginBottom: Spacing.md,
    borderWidth: 1, borderColor: Colors.border,
  },
  actionRow: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.md,
    paddingHorizontal: Spacing.md, paddingVertical: Spacing.md,
    borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  actionIcon: { width: 36, height: 36, borderRadius: Radius.sm, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { flex: 1, fontSize: FontSize.md, fontWeight: '600', color: Colors.text },
  settingsCard: { backgroundColor: Colors.card, borderRadius: Radius.lg, overflow: 'hidden', marginBottom: Spacing.md, borderWidth: 1, borderColor: Colors.border },
  settingRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.md, paddingVertical: Spacing.md,
    borderBottomWidth: 1, borderBottomColor: Colors.border, gap: Spacing.md,
  },
  settingInfo: { flex: 1 },
  settingLabel: { fontSize: FontSize.md, fontWeight: '600', color: Colors.text },
  settingDesc: { fontSize: FontSize.sm, color: Colors.textSecondary, marginTop: 1 },
  activeDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: Colors.success },
  tokenSmall: { fontSize: FontSize.md, fontWeight: '800', color: Colors.primary, letterSpacing: 2 },
  regenCard: {
    backgroundColor: Colors.card, borderRadius: Radius.lg,
    padding: Spacing.md, borderWidth: 1, borderColor: Colors.border,
  },
  regenBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: Spacing.sm, height: 48, borderRadius: Radius.lg,
    backgroundColor: Colors.primaryLight, marginBottom: Spacing.sm,
  },
  regenBtnText: { fontSize: FontSize.md, fontWeight: '700', color: Colors.primary },
  regenBtnTextLoading: { color: Colors.textMuted },
  regenNote: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center', lineHeight: 16 },
});
